### ISSUE TITLE
Highlighting blocks while tracing execution stops working after clicking on the workspace once

### ISSUE THREAD

**Issue by jstnhuang** [RaspberryPiFoundation/blockly#153]
Steps to reproduce (Chrome 44):
- Go to https://blockly-demo.appspot.com/static/demos/interpreter/index.html
- Click "Parse JavaScript"
- Click "Step JavaScript" once and notice the highlighting
- Click on a blank area of the workspace. The blocks are no longer highlighted
- Click "Step JavaScript" again. The blocks are still not highlighted.
- Click "Step JavaScript" several more times until the program finishes.

**Comment by NeilFraser** [comment]
Correct.  If a program is executing (maybe at one step per second) users want to be able to edit the program without stopping execution.  Once they start changing the selected block, Blockly automatically detaches from the executing program.  Otherwise the user would select a block, then have their selection stolen.

A concrete example is the Maze:
https://blockly-games.appspot.com/maze?level=10#hxrsmh
If you run that program, it will take a minute to complete.  Most will start editing the program without stopping it.  They want the original code to keep running while they make edits.
